[project]
name = "nolds"
version = "0.6.2"
description = "Nonlinear measures for dynamical systems (based on one-dimensional time series)"
authors = [
    {name= "Christopher Schölzel", email= "christopher.schoelzel@mailbox.org"}
]
license = "MIT"
license-files = ["LICENSE.txt"]
keywords = [
    "nonlinear",
    "dynamical system",
    "chaos",
    "lyapunov",
    "hurst",
    "hurst exponent",
    "rescaled range",
    "DFA",
    "detrended fluctuation analysis",
    "sample entropy",
    "correlation dimension"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
readme = "README.rst"
requires-python = ">=3.8"
dependencies = [
    "numpy>1.0,<3.0",
    "future>=1.0",
    "setuptools>=72.1.0"
]

[project.optional-dependencies]
RANSAC = ["scikit-learn>=0.19"]
qrandom = ["quantumrandom"]
plots = ["matplotlib"]

[dependency-groups]
dev = [
    "ruff>=0.11",
    # "keepachangelog>=2.0.0",
]

[project.urls]
Homepage = "https://github.com/CSchoel/nolds"
Repository = "https://github.com/CSchoel/nolds"
Issues = "https://github.com/CSchoel/nolds/issues"
Changelog = "https://github.com/CSchoel/nolds/CHANGELOG.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]

line-length = 100  # allow slightly longer lines
indent-width = 4

# Assume Python 3.8
target-version = "py38"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

[tool.ruff.lint]
# Select all rules by default
select = ["ALL"]
ignore = [
    "TD002", # adding an author to TODOs wastes space and is redundant because of git history
    "TD003", # once there is an issue, there is no need to keep the TODO => don't require links
    "COM812", # missing trailing commas are already fixed by the formatter
    "PLR0913", # this is a scientific library, functions just have a bazillion parameters
    "RUF002", # en-dashes are used for bibliographical references in docstrings
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
# source: https://github.com/astral-sh/ruff/issues/4368#issue-1705468153
"test/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG",  # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",  # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
    "INP001",  # Test folders should not have an `__init__.py`
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
