on:
  push:
    branches: ["main", "dev", "v*"]
  pull_request:

name: build

jobs:
  build:
    strategy:
      matrix:
        python: ["3.7", "3.10"]
        extras: ["", "[RANSAC, qrandom, plots]"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install ".${{ matrix.extras }}"
      - run: pip install codecov .
      - run: coverage run -m unittest nolds.test_measures
      - run: codecov
        if: ${{ matrix.python == '3.10' && matrix.extras != '' }}
