on:
  push:
    branches: ["main", "dev"]

name: build

jobs:
  build:
    strategy:
      matrix:
        python: ["2.7", "3.7", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install codecov .
      - run: coverage run -m unittest nolds.test_measures
      - run: codecov
        if: ${{ matrix.python == '3.10' }}
