on:
  push:
    branches: ["main", "dev", "v*"]
  pull_request:

name: build

jobs:
  build:
    strategy:
      matrix:
        python: ["3.8", "3.10"]
        extras: ["", "--all-extras"]
        include:
          - python: "3.8"
            os: ubuntu-22.04
          - python: "3.10"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync ${{ matrix.extras }} --python ${{ matrix.python }}
      - run: uv pip install codecov
      - run: uv run coverage run -m unittest nolds.test_measures
      - run: uv run codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.python == '3.10' && matrix.extras != '' }}
